solverClass : Z3Solver
problemClass : Z3Problem
declarationsClass : Z3Declarations
modelClass : Z3ModelWrapper
contextManagerClass : z3::context
literalClass : Z3Literal

problemConstraintType : z3::expr

contextSnippets :
  - context.hpp
  - implicate_printer.hpp
  - expr_storage.hpp
contextSrcSnippets :
  - context_src.cpp
  - storage_src.cpp
outputSnippets :
  - implicate_printer.hpp
solverInlineSnippets:
  - solver.hpp
problemSrcSnippets:
  - problem_src.cpp
solverSrcSnippets:
  - solver_src.cpp
parserSnippets :
  - parsers.cpp
abducibleSnippets :
  - generator_loader.cpp
  - generator_const_all_eq.cpp
  - generator_const_all_comp.cpp

parsers:
  -
    language : smtl2
    function : parse_Z3_SMT2 

abducibleGenerators:
  -
    name : constAllEq
    counter : countAbducibles_constAllEq
    generator : generateAbducibles_constAllEq
  -
    name : constAllComp
    counter : countAbducibles_constAllComp
    generator : generateAbducibles_constAllComp

abducibleLoader: loadAbducible

solverExceptions:
  -
    name : z3::exception
    messager : msg
