solverClass : CVC4Solver
problemClass : CVC4Problem
declarationsClass : CVC4Declarations
modelClass : CVC4ModelWrapper
contextManagerClass : CVC4::ExprManager
hypothesisClass : CVC4Hypothesis

problemConstraintType : CVC4::Expr

contextSnippets :
  - context.hpp
contextSrcSnippets :
  - string_utils.cpp
  - cvc4_utils.cpp
  - context_src.cpp
outputSnippets :
  - implicate_printer.hpp
solverInlineSnippets:
  - solver.hpp
problemSrcSnippets:
  - problem_src.cpp
solverSrcSnippets:
  - solver_src.cpp
parserSnippets :
  - parsers.cpp
abducibleSnippets :
  - generator_loader.cpp
  - generator_all_eq.cpp

parsers:
  -
    language : smtl2
    function : parse_CVC4_SMT2 
  -
    language : tptp
    function : parse_CVC4_TPTP
  -
    language : cvc4
    function : parse_CVC4_CVC4

abducibleGenerators:
  -
    name : allEq
    counter : countAbducibles_allEq
    generator : generateAbducibles_allEq
