solverClass : ts__solv
problemClass : ts__pbl
declarationsClass : ts__decls
modelClass : ts__mdl
contextManagerClass : ts__ctxm
hypothesisClass : ts__hy

problemConstraintType : int

contextSnippets :
  - context.hpp
contextSrcSnippets : []
outputSnippets : []
solverInlineSnippets: []
problemSrcSnippets:
  - problem_src.cpp
solverSrcSnippets:
  - solver_src.cpp
parserSnippets : []
abducibleSnippets :
  - dloader.cpp

parsers: []

abducibleGenerators: []
