solverClass : MinisatSolver
problemClass : MinisatProblem
declarationsClass : MinisatDeclarations
modelClass : MinisatModelWrapper
contextManagerClass : MinisatContextManager
hypothesisClass : MinisatHypothesis

problemConstraintType : Minisat::vec<Minisat::Lit>&

contextSnippets :
  - vector_wrappers.hpp
  - context.hpp
contextSrcSnippets : []
outputSnippets :
  - gpid_printers.hpp
solverInlineSnippets:
  - solver.hpp
problemSrcSnippets:
  - problem_src.cpp
solverSrcSnippets:
  - solver_src.cpp
parserSnippets :
  - parsers.cpp
abducibleSnippets :
  - generator_loader.cpp
  - generator_all.cpp

parsers:
  -
    language : dimacs
    function : parse_DIMACS

abducibleGenerators:
  -
    name : all
    counter : countAbducibles_all
    generator : generateAbducibles_all

abducibleLoader: loadAbducible

solverExceptions: []
